[WIP] Refer to vega's VALID_OPS
TODO
- [ ] Since this is only used in schema, should we install vega as dependency or devDependency?
- [ ] When I add the require('vega/src/...') I got the following error

```
Error: Cannot find module 'through'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kanitw/Documents/_code/_idl/_visrec/vega-lite/node_modules/vega/scripts/strip-schema.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Fixes #448, Fixes #613, Related #620